name: Daily Check-in Workflow

on:
  # 每天北京时间 03:00 执行任务
  schedule:
    - cron: '0 19 * * *'
  # 也可以手动触发
  workflow_dispatch:

jobs:
  checkin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List files in the current directory
        run: |
          ls -R

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Set environment variables
        env:
          # 阿里云盘
          ali_refresh_token: ${{ secrets.ALI_REFRESH_TOKEN }}
          # 蜜堂
          mtau: ${{ secrets.MTAU }}
          # 一点万象
          ydwx_deviceParams: ${{ secrets.YDWX_DEVICE_PARAMS }}
          ydwx_token: ${{ secrets.YDWX_TOKEN }}
          # 推送加
          plustoken: ${{ secrets.PLUSTOKEN }}
          # 贴吧
          tieback: ${{ secrets.TIEBA_COOKIE }}
          # iGot
          IGOT_PUSH_KEY: ${{ secrets.IGOT_PUSH_KEY }}
          # go-cqhttp
          GOBOT_URL: ${{ secrets.GOBOT_URL }}
          GOBOT_QQ: ${{ secrets.GOBOT_QQ }}
          GOBOT_TOKEN: ${{ secrets.GOBOT_TOKEN }}
          # gotify
          GOTIFY_URL: ${{ secrets.GOTIFY_URL }}
          GOTIFY_TOKEN: ${{ secrets.GOTIFY_TOKEN }}
          # 天翼云
          ty_username: ${{ secrets.TY_USERNAME }}
          ty_password: ${{ secrets.TY_PASSWORD }}
          # 女生社区
          nfsq_apitoken: ${{ secrets.NFSQ_APITOKEN }}
        run: |
          # 这里可以根据需要添加额外的环境变量设置或配置步骤

      - name: Run Alibaba Cloud Drive Check-in
        run: python aliyun.py  # 确保路径正确

      - name: Run MiTang Check-in
        run: python backup/mt.py  # 确保路径正确

      - name: Run Tieba Check-in
        run: |
          import os
          from tieba import Tieba  # 确保路径正确
          s = os.getenv("tieback").split('#')
          for i in range(len(s)):
              item = s[i]
              _check_items = [{"cookie": item}]
              tieba = Tieba(check_items=_check_items)
              msg = tieba.main()
              print(msg)
        shell: python

      - name: Run YidianWanxiang Check-in
        run: python ydwx.py  # 确保路径正确

      - name: Run Sina Weibo Topic Check-in
        run: |
          import os
          from Weibo import sign_topic  # 确保路径正确
          # 这里需要根据实际情况设置 title, action, params, headers
          # 示例：
          title = "示例超话标题"
          action = "示例action字符串"
          params = {}
          headers = {}
          message = sign_topic(title, action, params, headers)
          print(message)

      - name: Run Tianyi Cloud Check-in
        run: |
          import os
          from tyyun import main  # 确保路径正确
          global ty_username, ty_password
          ty_username = os.getenv("ty_username")
          ty_password = os.getenv("ty_password")
          main()

      - name: Run NvShengSheQu Check-in
        run: |
          import os
          from nfsq import do_task, goods_simple  # 确保路径正确
          apitoken = os.getenv("nfsq_apitoken")
          taskId = "示例任务ID"
          do_task(taskId, apitoken)
          goods = goods_simple(apitoken)
          print(goods)
